#!/bin/bash
# This script is executed after the app is rebuilt and deployed
echo "*** POST_DEPLOY ***"
# copy mysql database back into the app
cp -R ${OPENSHIFT_DATA_DIR}ca ~/mysql/data
# check if mysql database was restored properly
if [ -e ~/mysql/data/ca ]
then
    echo "mysql database 'ca' restored"
else
    echo "*** ERROR: mysql database 'ca' failed to restore! ***"
fi
# copy digital media back into the app
cp -R ${OPENSHIFT_DATA_DIR}media ${OPENSHIFT_REPO_DIR}php
# check if config.php was restored properly
if [ -e ${OPENSHIFT_REPO_DIR}php/media ]
then
    echo "digital media restored"
else
    echo "*** ERROR: digital media failed to restore! ***"
fi
# copy config files back into the app
cp -R ${OPENSHIFT_DATA_DIR}conf ${OPENSHIFT_REPO_DIR}php/app
# check if config.php was restored properly
if [ -e ${OPENSHIFT_REPO_DIR}php/app/conf ]
then
    echo "config files restored"
else
    echo "*** ERROR: config files failed to restore! ***"
fi
# copy setup.php back into the app
cp ${OPENSHIFT_DATA_DIR}setup.php ${OPENSHIFT_REPO_DIR}php
# check if config.php was restored properly
if [ -e ${OPENSHIFT_REPO_DIR}php/setup.php ]
then
    echo "setup.php restored"
else
    echo "*** ERROR: setup.php failed to restore! ***"
fi
# add writeable permissions to directories
#   (ref: http://docs.collectiveaccess.org/wiki/Installing_Providence#Installing_Providence_.28finally.21.29)
chmod 757 ${OPENSHIFT_REPO_DIR}php/app/tmp
chmod 757 ${OPENSHIFT_REPO_DIR}php/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache
chmod 757 ${OPENSHIFT_REPO_DIR}php/media
echo "added writeable permissions to media, tmp, and DefinitionCache directories"
