#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute before your application is stopped
# during your push.
# backup procedure: http://docs.collectiveaccess.org/wiki/Backing_up_a_CollectiveAccess_installation
echo "*** PRE_BUILD ***"
# backup mysql database
echo "backup mysql database..."
cp -R ~/mysql/data/collectiveaccess ${OPENSHIFT_DATA_DIR}
# backup digital media
echo "backup digital media..."
cp -R ${OPENSHIFT_REPO_DIR}php/media ${OPENSHIFT_DATA_DIR}
# backup config files
echo "backup config files..."
cp -R ${OPENSHIFT_REPO_DIR}php/app/conf ${OPENSHIFT_DATA_DIR}
# backup setup.php
echo "backup setup.php ..."
cp ${OPENSHIFT_REPO_DIR}php/setup.php ${OPENSHIFT_DATA_DIR}
